### ISSUE TITLE
PR runs showing up on https://wpt.fyi/results/?label=experimental

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1025]
https://wpt.fyi/results/?label=experimental and links like it have been passed around for a long time, and today https://wpt.fyi/results/preload?label=experimental&q=srcset was linked from [Intent to Ship: imagesrcset and imagesizes attributes on &lt;link>](https://groups.google.com/a/chromium.org/d/msg/blink-dev/07CbItWfA4M/CG1qF8IoEAAJ).

https://wpt.fyi/results/preload?label=experimental is very broken for Chrome and Firefox:
![image](https://user-images.githubusercontent.com/498917/51173608-0f38b580-18b6-11e9-9747-fc7107672be7.png)

That's because https://github.com/web-platform-tests/wpt/commit/7ca362d756 was a commit for https://github.com/web-platform-tests/wpt/pull/14847, and the run was an affected tests run on Taskcluster. The run doesn't seem to have been labeled correctly, however.

**Comment by foolip** [comment]
@lukebjerring can you take a look?

**Comment by lukebjerring** [comment]
This is an unfortunate consequence of enabling non-master runs in production.
I've enabled the query-builder yesterday, which should mitigate the need for manual construction of URLs, which exacerbate this problem, (because the default query + builder behaviour include `&label=master` by default).

**Comment by lukebjerring** [comment]
Closing this is WAI - include the `master` label if you want master-only runs.

**Comment by foolip** [comment]
I guess that different ways of making master implied based on other labels were considered and have other not-nice properties?

**Comment by foolip** [comment]
@fbeaufort was also bitten by this, but found this issue and the workaround.

**Comment by beaufortfrancois** [comment]
Could we redirect all requests with the `label=master` in the mean time if `label` is only `experimental` in the mean time?

**Comment by foolip** [comment]
I noticed/remembered https://wpt.fyi/results/?label=experimental is linked in ["Intent to {Implement,Experiment,Ship}" email templates for blink-dev](https://docs.google.com/document/d/1vlTlsQKThwaX0-lj_iZbVTzyqY7LioqERU8DK3u3XjI/edit#bookmark=id.dog2hyrj4r72). I've updated the link, but that's probably where some of the links have come from.

A redirect or other fix would be nice, there will be links in places that can't be updated too.

**Comment by foolip** [comment]
@gsnedders also ran into this, asked on IRC. I'll reopen since so many have reported it by now. Others have probably bumped into it without letting us know.

**Comment by lukebjerring** [comment]
Redirecting isn't great because it means that a query across all results becomes impossible, which can be a real problem in certain cases. We're not able to write a query for "this label OR that label". Forcing a mutually exclusive subset via redirect will just cause different headaches.

Again, this is not a problem with the behaviour of the label param, just that we now include things other than complete runs in the data. Building a permalink via the UI (after the next prod push) doesn't have this problem, i.e.:
- Visit wpt.fyi
- Click "EDIT" on the query banner
- Untick aligned
- tick master-only (#1023 will be fixed in #1034 is complete, and this will be the default)
- Change all channels to experimental
- Copy URL

@beaufortfrancois - For the case of just ?label=experimental, I'll make a PR with a toast suggesting that you might have meant to be looking at master runs, but a forced redirect isn't a great option. Thoughts?

**Comment by foolip** [comment]
A toast sounds good! To toasts!

**Comment by foolip** [comment]
@orphis was also bitten by this and asked me.
