### ISSUE TITLE
Edge and Safari runs for 5084587f6b are inaccessible / disappeared

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#110]
Updating the stats, in https://github.com/foolip/ecosystem-infra-stats/commit/b76615ebbdfbaa3966742adeae47e3ea1b86c0c5 I noticed something odd. For lots of PRs, runs for commit 5084587f6b were previously the earliest including run for Edge and Safari, and now it is cc364d6f98. The run creation date was "2018-04-27T04:05:13.060405Z" for Edge and "2018-04-26T06:31:34.263224Z" for Safari. The times for Chrome and Safari are different so this is probably not a mixup.

Now it looks like the Edge and Safari runs didn't happen at all:
https://wpt.fyi/?sha=5084587f6b

However, there are results for Edge and Safari in the storage bucket:
https://storage.googleapis.com/wptd/5084587f6b/edge-15-windows-10-sauce-summary.json.gz
https://storage.googleapis.com/wptd/5084587f6b/safari-11.0-macos-10.12-sauce-summary.json.gz

**Comment by foolip** [comment]
@jugglinmike knows about this.

**Comment by jugglinmike** [comment]
That's correct. The collection process for those browser/revision combinations was interrupted by [the resource starvation issue reported here](https://github.com/web-platform-tests/results-collection/issues/545). In order to preserve the integrity of data displayed on wpt.fyi, I manually modified the entities in the GPC Datastore. The project has an undocumented procedure for this: prefixing the "BrowserName" attribute of the invalid entity with the word "bad."

I apologize for the confusion caused by the ambiguity of this process. Given @hexcles' forthcoming redesign (and the low frequency of incidents), it probably doesn't make sense to change things too much right now. Here's what I propose:

- Change the "template" used to rename invalid entries from `bad{{browserName}}` to `{{browserName}}-invalid-gh-{{githubIssueNumber}}`
- Document this process in [the results-collector project](https://github.com/web-platform-tests/results-collection)

What do you think, @foolip?

**Comment by foolip** [comment]
Thanks @jugglinmike, I was confused because I didn't know about the convention for marking bad runs, and https://github.com/web-platform-tests/results-collection/pull/555 fixes that!
