### ISSUE TITLE
Azure artifacts exceed urlfetch limit and can't be ingested

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1227]
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=9985 is the latest scheduled run.

It failed with "API error: HTTP 400: Failed to fetch Azure artifact".

This may have been fixed by https://github.com/web-platform-tests/wpt.fyi/pull/1226, but it would also be good to ingest the missed runs.

**Comment by Hexcles** [comment]
Sigh this turns out to be a rather serious issue.

I forgot that in addition to the limit on the size of incoming requests, `urlfetch` also has a limit on the size of the response: [32MB](https://cloud.google.com/appengine/docs/standard/go/outbound-requests#quotas_and_limits_for_url_fetch).

I didn't warm up the cache for Safari & Edge, so the Azure artifacts are now easily over 32MB (80MB to be precise) with the screenshots of almost all failing reftests.

I need to move the artifact download into the processor.

**Comment by Hexcles** [comment]
I've reverted the Azure configuration changes in wpt for now so that screenshots are no longer included in the build artifacts.
