### ISSUE TITLE
Master runs from Taskcluster via Checks API cannot be ingested

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1240]
https://staging.wpt.fyi/runs?label=master&from=2019-03-15T00%3A00
https://wpt.fyi/runs?label=master&from=2019-03-15T00%3A00

After https://github.com/web-platform-tests/wpt/pull/15946 there have been no more runs, and no checks on PRs.

@Hexcles can you investigate and revert https://github.com/web-platform-tests/wpt/pull/15946 if we can't deploy a fix to prod today?

@jgraham FYI and sorry.

**Comment by Hexcles** [comment]
Turns out we have a multitude of fatal issues here.

First, the Taskcluster runs did not run any tests at all (this is https://github.com/web-platform-tests/wpt/issues/16026).

On the wpt.fyi side, there are multiple fatal bugs that would prevent TC runs from being ingested even if the TC setup was correct. For now, I'm sure of the following issues:
1. The user whitelisting feature does not play well with `check_run` completion events: these events are sent by a `ghost` user. In fact, we should only enforce whitelisting for triggering events and always respond to all completion events.
2. A server-side flag wasn't properly set.

**Comment by Hexcles** [comment]
So https://github.com/web-platform-tests/wpt.fyi/pull/1183#issuecomment-468309025 only verified that **PR** checks worked, but not master.

A fundamental difference between master and PRs is that master runs are sharded, so we should respond to `check_suite` events instead of individual runs so that we can merge all shards. (For a PR, we only care about the results of the affected tests, which are in a single run for each browser, so the approach in #1183 works.)

**Comment by foolip** [comment]
@Hexcles I see results now, is this fully fixed? Thanks a bunch in either case. If there's concrete monitoring we need to avoid this again, can you file issues?

**Comment by jgraham** [comment]
AIUI yhe checks API got disabled as that is still broken on the wpt.fyi side; what got fixed was not scheduling runs on master correctly.

**Comment by foolip** [comment]
Oh, reverted again in https://github.com/web-platform-tests/wpt/pull/16027.

@Hexcles any ETA on when it can be enabled again? Every time we flip back and forth required checks have to be disabled for a period, so any way to dry run it in prod first would be great.

**Comment by foolip** [comment]
@lukebjerring @Hexcles, has this been resolved or would things still break if we reland https://github.com/web-platform-tests/wpt/pull/15946?

(Noticed it again today because I was looking at a script for https://github.com/web-platform-tests/wpt/issues/14210.)

**Comment by Hexcles** [comment]
@foolip no it hasn't.

**Comment by lukebjerring** [comment]
> A fundamental difference between master and PRs is that master runs are sharded, so we should respond to check_suite events instead of individual runs

Actually, IIUC, Taskcluster still only does a single GitHub CheckRun in either case (the separated tasks/shards are not visible to GitHub, which just waits for the `completed` CheckRunEvent).

**Comment by Hexcles** [comment]
> Actually, IIUC, Taskcluster still only does a single GitHub CheckRun in either case (the separated tasks/shards are not visible to GitHub, which just waits for the completed CheckRunEvent).

https://github.com/web-platform-tests/wpt/pull/15583/checks?check_run_id=70458767

As you can see, each individual shard/job is a check run with different IDs.

**Comment by jgraham** [comment]
Should be a single check suite though, I assume.

**Comment by lukebjerring** [comment]
@Hexcles - what's the status here? Are we able to integration test this?

**Comment by lukebjerring** [comment]
@Hexcles - ping.

**Comment by jgraham** [comment]
Once https://github.com/taskcluster/taskcluster/pull/2477 we'l have the ability to write custom TC artifacts that are used in the checks summary page. This has the potential to fix many of the "I don't know how to understand the logs" problems we are seeing. Therefore I think we should bump the priority of this work since it's a blocker for that change.

**Comment by stephenmcgruer** [comment]
Closing since this should be fixed after https://github.com/web-platform-tests/wpt.fyi/pull/1971 (plus some follow-ups to it that happened). See https://github.com/web-platform-tests/wpt/issues/14846#issuecomment-644183897 for the roll-out plan.
