### ISSUE TITLE
Better Bug Tracking Workflow through GitHub Login for wpt metadata

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt.fyi#1408]
The current metadata amendment process is instruction-based and rather manual. It needs to open a PR against wpt-metadata repo and reviewed by the admins. See prototype [here](https://amend-metadata-dot-wptdashboard-staging.appspot.com/results/?label=master&label=experimental&aligned)

## Proposed workflow: 

- Sign in to your GitHub account

- Update the data in the UI, paste a bug number in this box and done

- Have the application push directly to master using your credentials

##  Possible Work:

GitHub login on wpt.fyi UI
Backend bits of auth, possibly through cookies?
/api/metadata/triage endpoint
Create and push a commit to wpt-metadata automatically

## Action Items:
What's the trade off, how easy is it to integrate with GitHub login? Better tradeoff than users have to 
create PRs in order to do failure triage

**Comment by KyleJu** [comment]
@lukebjerring @foolip

**Comment by Hexcles** [comment]
We can probably leverage [GitHub Apps](https://developer.github.com/apps/). wpt.fyi is already a GitHub app, but currently it only does Checks; and we'll need some [user-level permissions](https://developer.github.com/apps/building-github-apps/identifying-and-authorizing-users-for-github-apps) if we want to act on the user's behalf.

Alternatively, we can make a plain old OAuth App and store tokens. We shouldn't use cookies on either the server (not a great security practice) or the client (not feasible because of CORS).

**Comment by foolip** [comment]
I think that as long as we've authenticated the user, it's not important that we can act on GitHub on their behalf. We want to have the ability to block someone for abuse and to revert mistakes/sabotage, but that's all possible even if we push commits as a bot with the user's name in the commit message. Perhaps that would simplify the requirements here?

**Comment by jgraham** [comment]
Yeah, there are basically two options wrt auth. Option 1 is that we use the credentials of the user directly. That means the ACL for wpt-metadata determines who can commit and that everyone who triages has to be given direct write access. Option 2 is that we use a bot account to do the actual commits and the ACL can come from elsewhere (e.g. from wpt team membership). That has the advantage that it doesn't require us to be a GitHub App (although of course that's still possible) and it allows us to have people who can commit through the bot but not directly.

**Comment by foolip** [comment]
Yeah, if we don't want to allow everyone in the world to add metadata (try that first?) we can check for web-platform-tests org membership. That check requires the bot to have admin access to the org.

**Comment by foolip** [comment]
@KyleJu turns out that https://github.com/web-platform-tests/editor has GitHub login. You could grep that repo a bit to see how this might work, although I don't know if the simplest possible integration was used there.

**Comment by jgraham** [comment]
@KyleJu Are you planning to do the work here? This is important to us, so I'm happy to help out.

We want to use this for our own dashboard, which is pretty annoying, because afaict if wpt.fyi sets itself to allow GitHub login using the OAuth flow there isn't any way to make GitHub-auth requiring APIs accessible cross-origin, even if the x-origin caller gets its own set of access tokens. So it seems like we might need multiple implementations here.

**Comment by jgraham** [comment]
Oh I guess that's untrue; I would just need to make people log in at `wpt.fyi` and then POST to there from the dashboard with credentials enabled, so that cookies are sent. However this requires specific opt-in on the wpt.fyi side and @Hexcles expressed concern about using cookies here, so maybe there's a reason that won't work?

**Comment by Hexcles** [comment]
Sorry for the confusion, I was explaining some principles and best practices in web security to Kyle, and I was referring to user cookies on github.com, which the frontend of wpt.fyi does not have access to and the backend of wpt.fyi should never store. I did some more explanation later offline.

Now if we want to provide one-stop experience for editing metadata on wpt.fyi, we certainly have to use cookies (regardless of whether we want to modify files on users' behalf or using a bot account, we need to authenticate the users). I guess it is fine policy-wise since we are only identifying users who are editors of wpt and willingly log in? @foolip 

@jgraham are you describing a new feature request that you want to start the whole tracking flow from Mozilla's dashboard? It seems feasible (and yes we can explicitly set the headers to allow CORS from your dashboard), but I just want to make @KyleJu aware of the feature request here.

**Comment by jgraham** [comment]
> @jgraham are you describing a new feature request that you want to have the same one-stop editing support on Mozilla's dashboard via wpt.fyi? It seems feasible (and yes we can explicitly set the headers to allow CORS from your dashboard), but I just want to make @KyleJu aware of the feature request here.

Yes, that's the feature request. Sorry for all the confusion I've caused here.

**Comment by foolip** [comment]
Using cookies is fine. We can avoid setting any cookies until the user logs in, to put advisory information about cookies in that flow and not force it on everyone as happens on most sites accessed from Europe these days.

**Comment by KyleJu** [comment]
This has been fixed.
