### ISSUE TITLE
Only a subset of performance-timline tests are run in Safari

### ISSUE THREAD

**Issue by smfr** [web-platform-tests/wpt.fyi#1413]
https://wpt.fyi/results/performance-timeline?run_id=292600003 shows that only 17 of the ~40 tests are run in Safari. Many of the red tests here are simply not being run:

https://wpt.fyi/results/performance-timeline?label=master&label=experimental

How can we find out why these tests are not being run?

**Comment by Hexcles** [comment]
This is probably related to https://github.com/web-platform-tests/wpt/issues/18360 and https://github.com/web-platform-tests/wpt/issues/16229 . Safari runs are quite out of shape and STP is out of date recently.

**Comment by foolip** [comment]
I believe this is likely a case of https://github.com/web-platform-tests/wpt/issues/16229.

https://wpt.fyi/results/performance-timeline?run_id=290830008&run_id=276640004&run_id=280980002 shows a full Chrome run next to Safari runs with 4 and 8 jobs (from https://github.com/web-platform-tests/wpt/pull/18519). 3 more tests get run when Safari has 8 jobs.

However, the number of missing tests is still so large that I'm not confident this is entirely because of https://github.com/web-platform-tests/wpt/issues/16229, so I suggest leaving it open to confirm after that's been fixed. Assigning to @gsnedders to do so.

**Comment by foolip** [comment]
I did another run in https://github.com/web-platform-tests/wpt/pull/18519 with two problematic tests in inert/ deleted. Comparing again:
https://wpt.fyi/results/performance-timeline?run_id=290830008&run_id=276640004&run_id=288930005

That shows no "0 / 0" in the third column, confirming that this is a case of https://github.com/web-platform-tests/wpt/issues/16229. Closing as such.

**Comment by foolip** [comment]
A workaround has been landed and the latest aligned run now has results for Safari TP as well:
https://wpt.fyi/results/performance-timeline?run_id=281080007&run_id=276860005&run_id=289180009&run_id=276860007

@smfr it's clear that there are plenty of discrepancies between the browsers here, so I hope these results are useful. If you paste `chrome:pass firefox:pass safari:!pass` into the search box you'll see the tests that *only* fail in Safari, which might be the most useful thing to look at.
