### ISSUE TITLE
More aliases for the `count` atom

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1467]
https://github.com/web-platform-tests/wpt.fyi/blob/master/api/query/README.md#count is sweet and has aliases `one`, `two` and `three` already.

I'd like to suggest `none` and `all` queries as well. Examples I'd like to search for:
- `none(status:missing)` to exclude inconsistent subtest naming from other queries
- `all(status:error)` to find consistent harness errors

I guess `some` is not needed, because it's already implied.

**Comment by lukebjerring** [comment]
It's technically called `exists` rather than some, but yes, by default the root query is wrapped in an `exists` qualifier (i.e. there exists some result in the row where the query is true).

Right now the other root is `sequential`, which insists that each of its query items apply to the next result in sequence matching the runs. 

Re-using this pattern for all/none should be straightforward.

**Comment by foolip** [comment]
Would this replace the root condition? I do want to be able to say things like `is:different none(status:missing)` which works with `count:0` now.
