### ISSUE TITLE
Expose WebKitGTK in UI

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1576]
This issue is like https://github.com/web-platform-tests/wpt.fyi/issues/1575, but here it's the whole WebKitGTK product which is impossible to find via the UI.

**Comment by foolip** [comment]
@smfr you asked about this today https://webkit.org/meeting/. This is the tracking issue.

For now, this URL will always find you the latest aligned run of STP and WebKitGTK nightly:
https://wpt.fyi/results/?label=master&label=experimental&product=safari&product=webkitgtk&aligned

Or, if you'd like to also include Chrome and Firefox:
https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&product=webkitgtk&aligned

**Comment by foolip** [comment]
@clopez do you have an update on making a logo for WebKitGTK?

**Comment by clopez** [comment]
> @clopez do you have an update on making a logo for WebKitGTK?

We still don't have it. I will ping next week the people involved on the topic to see if we can move this forward

**Comment by stephenmcgruer** [comment]
Added in https://github.com/web-platform-tests/wpt.fyi/pull/1601, with the ephiphany logo for now.

This should be available in staging (https://wptdashboard-staging.appspot.com) soon, though a GitHub outage is currently holding everything up. It will also be available in the next prod release (usually done weekly, see same caveat about the GitHub outage :)).

Holding this open until it reaches staging.

**Comment by clopez** [comment]
I talked today with the person that was going to do a logo for WebKitGTK and he said he has not bandwith for it, so unfortunately i don't think we can have an official logo soon.

I was now just [comparing some runs of epiphany with WebKitGTK when i noticed this change adding the epiphany logo](https://staging.wpt.fyi/results/?diff&filter=ADC&run_id=271810016&run_id=253750013)

I think is fine for the moment using the epiphany logo

But I was wondering that maybe we can even think in replacing the daily runs of `webkitgtk_minibrowser` on taskcluster with `epiphany` runs?

The results are not exactly the same, but they are quite similar. With WebKitGTK/MiniBrowser is easier to enable more experimental features, but with Epiphany the results are more realistic to what people can expect to test. And making more easy to enable experimental features on Epiphany is something that can be worked on.

Perhaps this its less confusing for users, as everybody understands that "Epiphany" is a browser, but not sure if everybody will understand what is "WebKitGTK" ?

**Comment by stephenmcgruer** [comment]
I'm not sure I see a strong utility in running Epiphany over WebKitGTK (minibrowser) here. I also don't see a particularly strong utility in WebKitGTK over Epiphany, but we already have it running so the comparison is naturally in the other direction :)

One of our main goals with the WebKitGTK runs was to have another data point to compare to Safari (both stable and TP), to help with reliability issues for Safari runs. It's not clear to me that using Epiphany would help there - the lack of experimental features seems concerning to start with (i.e. is there a version of Epiphany comparable to TP?).

> Perhaps this its less confusing for users, as everybody understands that "Epiphany" is a browser, but not sure if everybody will understand what is "WebKitGTK" ?

Our users tend to be either browser engineers looking to investigate a feature, or technical leaders trying to understand and prioritize work. I suspect that for browser engineers they would be concentrating on browsers they are familiar with anyway (probably Chrome/Edge/Firefox/Safari), and for the latter they would be familiar with WebKitGTK if it was useful for them to be.

**Comment by Hexcles** [comment]
> Holding this open until it reaches staging.

This has reached staging.

**Comment by mcatanzaro** [comment]
> I think is fine for the moment using the epiphany logo

Well it's legally fine since it's Creative Commons, but that's comparable to using an Edge logo to display test results for Google Chrome. Yeah the test results will be almost the same, but you wouldn't likely do that. I request you please do not use our logo for test results not actually gathered with Epiphany. There are plenty of other generic web browser logos you could use in a pinch instead, e.g. the web-browser logo from Adwaita or any desktop icon theme.

As for using Epiphany rather than MiniBrowser for test results, that would be cool.

> One of our main goals with the WebKitGTK runs was to have another data point to compare to Safari (both stable and TP), to help with reliability issues for Safari runs. It's not clear to me that using Epiphany would help there - the lack of experimental features seems concerning to start with (i.e. is there a version of Epiphany comparable to TP?).

That would be Epiphany Technology Preview (which has a slightly different logo). However, we do not enable experimental features unless those features are intended to be stable in the next stable release of WebKitGTK (in which case, we would adjust the internal WebKit settings such that they are no longer experimental) because the goal, like Safari Tech Preview, is to be a usable daily browser. Whereas WebKit experimental features are actively tested in Safari, they are not tested in WebKitGTK and often have severe platform-specific bugs. (Also, WebKitGTK does not have any API to enable experimental features at runtime, so it wouldn't be possible to do anyway, but that's not the primary reason.) There are a few other differences from Safari Tech Preview with regard to update cadence (WebKitGTK updates monthly instead of biweekly, and I have rejected the last two updates due to major regressions so we're far behind currently) but the goal is to be as close to Safari TP as it's possible to be without major regressions.

**Comment by stephenmcgruer** [comment]
> Well it's legally fine since it's Creative Commons, but that's comparable to using an Edge logo to display test results for Google Chrome. Yeah the test results will be almost the same, but you wouldn't likely do that. I request you please do not use our logo for test results not actually gathered with Epiphany. There are plenty of other generic web browser logos you could use in a pinch instead, e.g. the web-browser logo from Adwaita or any desktop icon theme.

Absolutely reasonable request, but I would *really* like to switch to using a proper WebKitGTK logo, and as far as I understand it, Igalia are the ones that can make that happen :). I'll look into finding a generic browser logo in the meantime.

> That would be Epiphany Technology Preview (which has a slightly different logo). However, we do not enable experimental features unless those features are intended to be stable in the next stable release of WebKitGTK (in which case, we would adjust the internal WebKit settings such that they are no longer experimental) because the goal, like Safari Tech Preview, is to be a usable daily browser. Whereas WebKit experimental features are actively tested in Safari, they are not tested in WebKitGTK and often have severe platform-specific bugs. (Also, WebKitGTK does not have any API to enable experimental features at runtime, so it wouldn't be possible to do anyway, but that's not the primary reason.) There are a few other differences from Safari Tech Preview with regard to update cadence (WebKitGTK updates monthly instead of biweekly, and I have rejected the last two updates due to major regressions so we're far behind currently) but the goal is to be as close to Safari TP as it's possible to be without major regressions.

To check I'm reading this correctly, you do attempt to have the same experimental features as Safari TP enabled in Epiphany TP, but have historically found that some (many?) of the features turned on in Safari TP have platform-specific bugs that cause them to be withheld from Ephiphany TP? Then on top of that, Epiphany TP releases may be out of sync with Safari TP, which means one may pull ahead of the other? Just gathering my data atm :)

**Comment by mcatanzaro** [comment]
> To check I'm reading this correctly, you do attempt to have the same experimental features as Safari TP enabled in Epiphany TP

No, because WebKitGTK does not have an experimental features API comparable to Apple's. It's simply not possible to enable WebKit experimental features in WebKitGTK like it is using Apple's WebKit APIs. Doing so would require adding new WebKitGTK API for exposing runtime-enumerable features. Instead, WebKitGTK has a settings API that exposes a handpicked small minority of WebKit's internal settings in the WebKitGTK public API, and these are all individual permanent settings APIs rather than one API for retrieving a list of the current experimental features like the Apple API offers. WebKitGTK also has a special build flag -DENABLE_EXPERIMENTAL_FEATURES=ON that can be used to enable a couple particular experimental features, but we use this only for features in a bad state, so Tech Preview does not enable this build flag; once they are in good enough state such that they could plausibly be enabled in the next stable release at the current pace of development, then we would enable them without requiring this build flag. (Currently WebRTC is the big one stuck at this stage. Until recently, ServiceWorkers was too.)

In practice, most experimental features are either (a) quickly developed, graduated to stable, and enabled by default, so not having experimental features in Tech Preview doesn't really matter as they'll show up soon enough regardless; or (b) quickly developed, stabilized, and forgotten about because WebKit developers are bad at managing the cross-platform preferences definitions, which would be easy to fix by simply reviewing the preferences definitions more quickly; or (c) broken or in bad state for years due to platform-specific issues and lack of platform-specific development, which we don't want enabled until they improve. Usually big-name features that we care about are likely to fall squarely under (c).

This all affects MiniBrowser exactly the same as it does Epiphany, so I'm not sure what difference in behavior there is from MiniBrowser, unless WPT's MiniBrowser builds with the -DENABLE_EXPERIMENTAL_FEATURES=ON build flag. That build flag force-enables all the Safari experimental features that are enabled by default in Safari TP, but none of the experimental features that are disabled by default. There's no way to toggle them enabled/disabled.

OK, with all that out of the way: that status quo might not seem great, but for Ephy it's perfectly fine because there is an important audience difference here. Web developers probably don't even know Epiphany exists, and certainly wouldn't care about it if they did know. Epiphany TP is used primarily by Ephy fans who want something newer than the system-provided Ephy. For me, the goal is to help test the next version of WebKitGTK, and having features enabled that are not targeted for the next WebKitGTK release would be really unhelpful for that goal. Once they're targeted for the next release (by making them non-experimental), then they will be enabled, and that's good enough for us. So even if we were to add experimental features APIs comparable to Apple's, I would still be disinclined to enable experimental features by default in Tech Preview. We could surely figure out some sort of opt-in, e.g. for use by WPT if desired. Exception would be WebRTC, because that feature requires building GPL-incompatible code and linking the web process to it. Epiphany has a lot of GPL code in its web process, so WebRTC must be disabled at build time until that's solved.

> but have historically found that some (many?) of the features turned on in Safari TP have platform-specific bugs that cause them to be withheld from Ephiphany TP?

I would say "some." I suppose most features are truly platform-agnostic and don't have platform-specific bugs. (But the most important experimental features, the ones you want to use, probably do. Otherwise, we'd make them non-experimental.)

> Then on top of that, Epiphany TP releases may be out of sync with Safari TP, which means one may pull ahead of the other? Just gathering my data atm :)

Both Tech Previews are released off WebKit trunk (except Epiphany TP switches to a stable branch for a short while before and after a new major stable release of WebKitGTK), but at different times. Safari TP tries to release roughly every two weeks. WebKitGTK tries to do unstable releases roughly monthly, but sometimes less often (or more often). If Safari TP is in bad state the release will be delayed a bit until it is good, whereas if a WebKitGTK release is sufficiently bad then Ephy TP usually waits another month and hopes for the best next month (which I would love to see improved, so that we can move faster). Currently we have been stuck on a stable branch since August, much longer than usual, due to specific problematic regressions in the recent unstable releases.

Whereas WebKit is updated roughly monthly, most other dependencies (GTK, GLib, etc.) are built from git master and updated daily. Epiphany itself is updated immediately whenever there is a new commit. This all *generally* works out fine since it's the WebKit updates that are riskiest.

**Comment by mcatanzaro** [comment]
> Currently we have been stuck on a stable branch since August, much longer than usual, due to specific problematic regressions in the recent unstable releases.

BTW this is really bad, but we have to balance user experience vs. having the latest code. Ideally I'd love to do biweekly releases like Safari TP, but I don't control the WebKitGTK release cycle and I understand it's considered too much work to release every two weeks.

**Comment by clopez** [comment]
> This all affects MiniBrowser exactly the same as it does Epiphany, so I'm not sure what difference in behavior there is from MiniBrowser, unless WPT's MiniBrowser builds with the -DENABLE_EXPERIMENTAL_FEATURES=ON build flag. 

The version of WebKitGTK that is tested on the WPT CI is built with `ENABLE_EXPERIMENTAL_FEATURES=ON` 

Regarding WebKitGTK MiniBrowser and Epiphany features, what I meant is that with MiniBrowser is currently possible to enable any run-time feature exposed in the GLib API via a command-line switch. But that is not currently possible with Epiphany (for example for EME or WebRTC experimental features, that are interesting for WPT tests). [This is what it is getting currently enabled for WTP tests with WebKitGTK MiniBrowser](https://github.com/web-platform-tests/wpt/blob/928d8accde/tools/wptrunner/wptrunner/browsers/webkitgtk_minibrowser.py#L37)

> That build flag force-enables all the Safari experimental features that are enabled by default in Safari TP, but none of the experimental features that are disabled by default. There's no way to toggle them enabled/disabled.

I have worked recently on changing some of this run-time features (the ones not exposed in the GLib API) that were "disabled by default" to be "enabled if experimental features are enabled". So, if you build WebKitGTK with experimental features enabled (we do that for WPT tests) then I think it will be very similar to Safari TP with all experimental features enabled.

**Comment by mcatanzaro** [comment]
> But that is not currently possible with Epiphany (for example for EME or WebRTC experimental features, that are interesting for WPT tests).

We can maybe add a setting for EME if you really need it for WPT testing, although it would be a bit weird to do so for just useless ClearKey. I'd probably want to give the setting a test-related or temporary-sounding name to make clear to users that it's not going to function as desired. The case to add a setting would be a lot stronger if it could do something useful for users.

We can't add a setting for WebRTC, though, because WebKit's implementation is not GPL-compatible. That runtime setting doesn't work anyway (unless you build WebKit from git) since libwebrtc isn't distributed in releases. i.e. the API has been broken in every release.

**Comment by clopez** [comment]
> We can maybe add a setting for EME if you really need it for WPT testing, although it would be a bit weird to do so for just useless ClearKey. I'd probably want to give the setting a test-related or temporary-sounding name to make clear to users that it's not going to function as desired. The case to add a setting would be a lot stronger if it could do something useful for users.

I think that having test results for the WebKitGTK EME implementation is definitively interesting (even when for using EME on a real website you need a propietary CDM, which is not available for Epiphany, the implementation itself of EME can still be tested with the ClearKey CDM)

> We can't add a setting for WebRTC, though, because WebKit's implementation is not GPL-compatible.

IANAL, but I don't think there is any license issue, because Epiphany doesn't link with BoringSSL when WebRTC is enabled on WebKitGTK due to the process separation architecture of the WebKit2 model.

> That runtime setting doesn't work anyway (unless you build WebKit from git) since libwebrtc isn't distributed in releases. i.e. the API has been broken in every release.

Indeed, we are building from SVN/git for the nightly channel.
For the stable channel an extra tarball with the corresponding libwebrtc directory is currently being added manually when building the package.
I think properly distributing libwebrtc in release tarballs is something that we should fix soon.

**Comment by mcatanzaro** [comment]
> IANAL, but I don't think there is any license issue, because Epiphany doesn't link with BoringSSL when WebRTC is enabled on WebKitGTK due to the process separation architecture of the WebKit2 model.

If that worked, we should have enabled WebRTC years ago. :P You forget the web process extension. Epiphany's web process extension is GPLv3+ and does not have any license exception for BoringSSL. Talking to Phil, we see a clear path forward: switch WebKit to use gstwebrtc, which uses OpenSSL instead of BoringSSL, and then wait for OpenSSL 3.0 to be released (the upcoming version of OpenSSL that will use Apache license).

> I think properly distributing libwebrtc in release tarballs is something that we should fix soon.

My $0.02: if you distribute the code before the license problems are fixed, you're just setting up a license compatibility trap for distros. And since the way to fix the problems is to stop using libwebrtc, you should never need to dist it. :)
