### ISSUE TITLE
`link` atom does not appear to function correctly

### ISSUE THREAD

**Issue by stephenmcgruer** [web-platform-tests/wpt.fyi#1757]
See the following search: https://wpt.fyi/results/WebIDL/ecmascript-binding/default-iterator-object.html?label=experimental&label=master&product=chrome&product=firefox&product=safari&aligned&q=chrome%3A%21pass%20chrome%3A%21missing%20safari%3Apass%20firefox%3Apass%20%21link%3Abugs.chromium.org

This specifies `chrome:!pass chrome:!missing safari:pass firefox:pass !link:bugs.chromium.org`, but the result that is shown has 'bugs.chromium.org' metadata associated with it. I would expect this search result to be empty.

You can also see this at the top-level. At time of writing, https://wpt.fyi/results/?label=experimental&label=master&aligned says `Showing 38482 tests (1704824 subtests)`. Searching `link:bugs.chromium.org` says `Showing 37 tests (11445 subtests)`. But searching `https://wpt.fyi/results/?label=master&label=experimental&aligned&q=%21link%3Abugs.chromium.org` says `Showing 38479 tests (1704808 subtests)`, which is not the result of subtracting the two previous queries!

There's some funky stuff going on with this atom

**Comment by KyleJu** [comment]
I just remembered that `chrome:!pass chrome:!missing safari:pass firefox:pass !link:bugs.chromium.org` is missing in the initial development. `!link:` currently only works with a single browser, such as finding untriaged single browser failures. IIUC, `Filter()` is filtering the result of a single browser at a time, and the test results are aggregated and shown if a search atom is passing in any of the browsers for the same test name.

For example, [searching !link:bugs.chromium.org under wpt /FileAPI on safari and chrome](https://wpt.fyi/results/FileAPI?label=master&label=experimental&product=chrome&product=safari&aligned&q=chrome%3Afail%20safari%3Apass%20%21link%3Abugs.chromium.org) vs [searching only on chrome](https://wpt.fyi/results/FileAPI?label=master&label=experimental&product=chrome&aligned&q=chrome%3Afail%20safari%3Apass%20%21link%3Abugs.chromium.org), where searching on chrome is working as intended.

Only way to solve this is to add browser information in the link atom, such as !chromeLink:bugs.chromium.org.

`link` without `!` should work correctly otherwise.

**Comment by KyleJu** [comment]
Chatted offline with @stephenmcgruer. Instead of improving the existing `!link` search atom, it makes sense to support #1760 first

**Comment by KyleJu** [comment]
Found a workaround using None, [none(link:bugs.chromium.org) and chrome:!pass and chrome:!missing and safari:pass and firefox:pass](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=none%28link%3Abugs.chromium.org%29%20and%20chrome%3A%21pass%20and%20chrome%3A%21missing%20and%20safari%3Apass%20and%20firefox%3Apass%20)
