### ISSUE TITLE
Set up health checks

### ISSUE THREAD

**Issue by mdittmer** [web-platform-tests/wpt.fyi#177]
According to this:

https://cloud.google.com/appengine/docs/flexible/custom-runtimes/configuring-your-app-with-app-yaml#health_checks

A project-wide setting is used to enable/disable "split health checks" (as opposed to "legacy health checks" which will go away this September).

Right now, `wptdashboard` is set to the default "legacy health checks". We should probably switch to split health checks with appropriate configurations on all services. From what I understand this would look like:

1. Land changes to all `app.yaml` files that appropriately configure split health checks;
1. Switch, project-wide to split health checks with `gcloud app update --split-health-checks --project wptdashboard`;
1. Redeploy all services to ensure that they are configured appropriately with respect to the project-wide health check configuration.

@Hexcles and @lukebjerring do you want to own config changes for receiver and webapp (resp.), and I'll handle the announcer?

**Comment by Hexcles** [comment]
Yeah I can take care of my Flex service (processor).

It's relatively low priority since the default legacy health check seems to meet my needs so far.

**Comment by Hexcles** [comment]
When @mdittmer discussed this with me offline a couple of days ago, I said that I didn't believe there was a project-level setting for health checks. I was not exactly correct. There's indeed a project level setting as linked at the top, but the setting doesn't really do much: it will (supposedly) give an error if custom legacy health checks are used in the project; otherwise, it simply switches from default legacy health checks to default split health checks (which isn't really noticeable).

And even without tweaking that project-level setting, uploading an `app.yaml` with custom split health checks will turn on split health checks for the corresponding service.

Both the receiver (#187) and the announcer (#262) are already using split health checks. There's not much need to switch the webapp to split health checks for now. So I'd consider all work done here! :)
