### ISSUE TITLE
Triaging can overwrite existing metadata

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1890]
https://github.com/web-platform-tests/wpt-metadata/pull/147 overwrote the changes from https://github.com/web-platform-tests/wpt-metadata/pull/146. It looks it just created the META.yml file and replaced what was in the repo.

**Comment by foolip** [comment]
I tried to undo it, but https://github.com/web-platform-tests/wpt-metadata/pull/148 just reverted it again. How long does one have to wait?

**Comment by KyleJu** [comment]
@foolip: It takes 10 minutes to update metadata cache with the latest commit. 

The correct behavior for web-platform-tests/wpt-metadata#147 is to produce a diff with web-platform-tests/wpt-metadata#146. The cause of the issue is twofold (1) out-of-date metadata cache (2) the commit API pushes entire files, which overwrite the existing files.

**Comment by stephenmcgruer** [comment]
> The correct behavior for web-platform-tests/wpt-metadata#147 is to produce a diff with web-platform-tests/wpt-metadata#146. The cause of the issue is twofold (1) out-of-date metadata cache (2) the commit API pushes entire files, which overwrite the existing files.

It would also be 'fine' if we based the branch created for #147 on the commit we have **cached**, rather than on upstream master (which had moved onto #146). You would get a merge conflict, but that's better than overwriting things silently.

**Comment by KyleJu** [comment]
Per discussions online, we can

1. I suspect there is a way to find the correct base branch for the PR and produce the diff correctly
2. Use a different commit API. (If I remember correctly) there is an API that inserts changes into latest commit of the repo instead of pushes entire files.
3. Check if the local cache is out of date and fetch on demand. This wouldn't work if two consecutive commits are within a 2-minutes interval, because CI checks take two minutes
4. Accumulate changes  on the server side

In addition, we need to find a way to fix the displayed metadata due to the same issue and warn users if a metadata has been triaged

**Comment by KyleJu** [comment]
> > The correct behavior for [web-platform-tests/wpt-metadata#147](https://github.com/web-platform-tests/wpt-metadata/pull/147) is to produce a diff with [web-platform-tests/wpt-metadata#146](https://github.com/web-platform-tests/wpt-metadata/pull/146). The cause of the issue is twofold (1) out-of-date metadata cache (2) the commit API pushes entire files, which overwrite the existing files.
> 
> It would also be 'fine' if we based the branch created for #147 on the commit we have **cached**, rather than on upstream master (which had moved onto #146). You would get a merge conflict, but that's better than overwriting things silently.

Right, I suspect I didn't set the base branch right in the API, which would be the easiest way to fix this.

**Comment by foolip** [comment]
> Use a different commit API. (If I remember correctly) there is an API that inserts changes into latest commit of the repo instead of pushes entire files.

I thought this was already the case based on discussions, but never looked at any of the code. Can you point to the code that creates the branches for these PRs?

**Comment by KyleJu** [comment]
> > Use a different commit API. (If I remember correctly) there is an API that inserts changes into latest commit of the repo instead of pushes entire files.
> 
> I thought this was already the case based on discussions, but never looked at any of the code. Can you point to the code that creates the branches for these PRs?

[code](https://github.com/web-platform-tests/wpt.fyi/blob/master/shared/triage_metadata.go#L157). Thats indeed the case for /api/metadata/triage. What I meant is GitHub APIs we use, create a blob and overwrites entire files. I think I have seen an API that doesn't overwrite

**Comment by Hexcles** [comment]
Regarding why there was no merge conflict, I think the problem here is that the API sets the wrong parent when committing changes.

https://github.com/web-platform-tests/wpt.fyi/blob/111641e0cefbfee98cda2c83a7ba360bf7d31668/shared/triage_metadata.go#L98

The API is using the head of the master branch as the parent, so naturally git thinks that we are trying to overwrite the file and gives no merge conflict.

We should be using the SHA of the cached metadata instead. That way you'll see merge conflicts as expected.

This does NOT solve the usability issue though. I think it makes sense to try to update the cache right before updating the yaml file. There'll still be race conditions, but at least much less likely.
