### ISSUE TITLE
Triaging same test twice results in unclear wpt-metadata PR failure

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#1895]
https://github.com/web-platform-tests/wpt-metadata/pull/157 was created after I triaged the same test twice, not sure which test I successfully got triaged yesterday.

The created PR adds a duplicate entry, and then fails some check on the PR. It would be better if it's instead a no-op, or if the failure is very explicit about what has done wrong.

**Comment by KyleJu** [comment]
Per my offline discussion with Rob, instead of a no-op, I would still prefer that a PR can be successfully created, in case that a user wants to overwrite the existing metadata. However, /api/metadata/triage should return a warning message about the duplicated entries. The response should be a JSON object, instead of text. E.g. `{"message": "Test foo is a duplicated entry", "PR": "github.com/foo123"}`. This is a breaking change on the Mozilla WPT dashboard and wpt.fyi side.

Note to myself: confirm with jgraham about this API change

**Comment by KyleJu** [comment]
Note that the reason the author triaged the same tests twice is that the triaged tests are not reflected in the UI immediately. This issue is blocked by https://github.com/web-platform-tests/wpt.fyi/issues/2202

**Comment by KyleJu** [comment]
#2202 will allow users to avoid this issue
