### ISSUE TITLE
Black Lives Matter solidarity statement

### ISSUE THREAD

**Issue by isaacdurazo** [web-platform-tests/wpt.fyi#2039]
Hi WPT Team 👋🏽, I've been helping to add Black Lives Matter solidarity statements to some project's websites (like [Test262 Report](https://test262.report) and [P5.js](https://p5js.org/)) and would love to do the same for WPT. Perhaps something similar to what [emberjs.com](https://emberjs.com/) has implemented in its website. What do you think?

If this is ok with you I can take care if submitting a PR with the changes.

**Comment by stephenmcgruer** [comment]
Hi Issac; thanks for reaching out and sorry for the delay in anyone getting back to you.

Let me @web-platform-tests/wpt-core-team to make sure folks see this, but this seems like a great idea to me.

There are two possible places we could add this to (that I can think of). https://web-platform-tests.org/ is the documentation site for the test suite, and is built via Sphinx out of files in `docs/` in this repo. https://wpt.fyi on the other hand, is developed separately from WPT and probably needs its own issue opened in https://github.com/web-platform-tests/wpt.fyi for that.

**Comment by jgraham** [comment]
Definitely no objections to this, but I feel like it would be more meaningful if there were associated actions; it's relatively easy to make a website display a message, and relatively hard to think through our choices and impact on society to ensure we're actually living out the proclaimed values. That said I don't know specifically what those actions should be. Working to improve open-access technology rather than walled gardens seems on its own like a societal good, but perhaps not too directly relevant. We have in the past had interns from Outreachy (via employers), which seems good in terms of providing an entry point to the industry for people in under represented minorities, but we don't specifically have any commitment to do similar things going forward. Arguably making extensive use of GitHub is problematic due to the ICE thing. Suggestions here are very welcome.

**Comment by Hexcles** [comment]
As a core maintainer of wpt.fyi, I'm supportive of this. I'm going to send a PR to add a simple banner for now. It'd probably be better to link to somewhere, but we can work on that latter.

James has raised a good point about actions. In case anyone hasn't noticed, we have been proactively changing the codebase to use more inclusive terminologies. And I encourage everyone to read https://tools.ietf.org/id/draft-knodel-terminology-00.html

**Comment by isaacdurazo** [comment]
Hey folks, thanks so much for considering and supporting this idea!

I agree with you all that incorporating this banner without associated actions focused on social justice might not be meaningful enough, but at the same time I think is a great start to show support for the BLM movement. 

One thing that I think could be done to address diversity and inclusiveness is to incorporate resources such as educational materials like [wpc.guide](https://wpc.guide/) that could serve as an onramp for beginners, especially from underrepresented groups. We (Bocoup) have been working on this guidebook and would be open to changes so that the WPT community are comfortable using or endorsing it.
