### ISSUE TITLE
"Browser Specific Failures graph" using stable by default

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt.fyi#2394]
It feels surprising that that graph uses stable by default while all the results below are for "experimental". (It's also marginally surprising that the set of browsers differs, even though clearly including Edge there is meaningless.)

**Comment by stephenmcgruer** [comment]
Yep, that makes a lot of sense. @KyleJu - wdyt of making experimental the default? It's also arguably the better view for devs since it changes a *lot* faster than stable as fixes are landed.

On Edge, I agree - we still intend to remove Edge from the default set of projects but haven't found the time to do so (based on the agreed plan it does require us to leave some sort of breadcrumb for folks to add edge back)
