### ISSUE TITLE
Append 'stable' / 'experimental' labels to the uploaded TestRun entities

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#245]
This would support wpt.fyi's default view switch to the 'stable' label, which means that arbitrary runs aren't shown on the dashboard by default.

**Comment by lukebjerring** [comment]
Building off #212 and #240

**Comment by lukebjerring** [comment]
cc @jugglinmike - this is information available during execution. While we need to continue to name the browsers `[browser]-experimental`, we also need to include the `experimental` label in the uploaded run (and `stable` for the non-experimental runs) to support the intended change to wpt.fyi's default query (?label=stable).

**Comment by jugglinmike** [comment]
Got it. Can you explain how the label should be specified in each receiver system?

**Comment by Hexcles** [comment]
In the new world of results receiver, the browser names in the uploaded reports *won't* contain the `-experimental` suffix, because the names are directly from the argument of `wpt run` (well, except Sauce runs).

I'm thinking the runner can add a `labels` param in the payload when uploading results, which is a comma-separated string of labels (the payload is a form instead of JSON so we don't have real arrays). The labels can be quite free-form. For this issue, we can simply add the [`browser_channel`](https://github.com/web-platform-tests/results-collection/blob/19aab09fe38e55c78d47e582e5599dd58de1076b/src/master/browsers.json) as a label.

(Note: runners don't need to change the legacy upload at all. Just keep the name spoofing as is for now. And we'll soon remove the whole legacy upload altogether.)

The receiver creates test runs with the vanilla browser names and add the 'stable'/'experimental' label. The webapp needs to be changed to filter experimental runs by: the browser name ends with `-experimental` **OR** the run has the `experimental` label (so that history experimental runs are still recognized).

**Comment by Hexcles** [comment]
> The webapp needs to be changed to filter experimental runs by: the browser name ends with -experimental OR the run has the experimental label (so that history experimental runs are still recognized).

Sorry, this is already the case.
