### ISSUE TITLE
[compat2021] responsive layout for narrow screens

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#2494]
https://wpt.fyi/compat2021?feature=summary&embedded when embedded on wpt.fyi in an iframe gets horizontal scrollbars for narrow screens, the breakpoint probably being 800px judging by the width of the graph component.

For wpt.fyi as a whole it has never seemed important to make it work well on small screens, but for this dashboard it would be useful. I would not say it's super important, however.

**Comment by stephenmcgruer** [comment]
FYI, the embedded form has nothing to do with the rest of wpt.fyi; it entirely (afaik) removes all CSS/HTML that is used for wpt.fyi

The problem here is the graph, as noted in the OP. Specifically the fact that Google Charts width is set at draw time (even if one uses `width: 100%` in the chart options), and will not resize dynamically with the page. To fix this, I believe we could:

1. Set https://github.com/web-platform-tests/wpt.fyi/blob/main/webapp/components/compat-2021.js#L709 to `"100%"` rather than `800`, and style the parent element accordingly.
2. Add a resize handler to redraw the chart when the page size changes.

We could do just the first one if we only wanted an initial lower-sized load to work and don't care about supporting resize.
