### ISSUE TITLE
Score for "passing in all browsers" on Interop 2022 dashboard

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#3005]
This was suggested by @karlcow in https://github.com/web-platform-tests/interop/issues/198 and discussed in https://github.com/web-platform-tests/interop/issues/209.

@DanielRyanSmith can you look into what it would take to implement this? I suspect that https://github.com/web-platform-tests/results-analysis would need to be updated, we can't get this from the existing data files.

**Comment by DanielRyanSmith** [comment]
Some more info on this - we are pulling the stats on these scores from a CSV created by the results-analysis code, which scores each focus area with a 0-1000 score for each browser and each date interval. Here is the [CSV for experimental runs for Interop 2022](https://raw.githubusercontent.com/web-platform-tests/results-analysis/gh-pages/data/interop-2022/interop-2022-experimental.csv).

The difficulty here comes with determining which tests/subtests pass in every browser. Since the current CSV format only has a score for each focus area, we can't derive this information because we can't see exactly which test/subtests are failing to determine where fails/passes are overlapping. It also depends on how detailed we need to be. Do we want to see the progression of this statistic over time? If we only care about the current state, it might be possible to calc this separately from the current CSV by looking at the latest run.


However, my suggestion would be to calc this over time like all the other scores, adding new columns to the CSV for each focus area, similar to a separate browser score.

Current CSV format (showing only aspect-ratio focus area as an example):
| date | chrome-version | chrome-aspect-ratio | firefox-version | firefox-aspect-ratio | safari-version | safari-aspect-ratio |
|---|---|---|---|---|---|---|
| 2022-10-20 | 108.0.5359.10 dev | 987 | 108.0a1 | 993 | 156 preview | 987 |

New column:
| overall-aspect ratio |
|---|
| 986 |

This would require a change in the results-analysis code, a UI update on wpt.fyi, as well as a change to the CSV parsing code on the client side of wpt.fyi. This is a manageable change if it is deemed worth implementing.

**Comment by karlcow** [comment]
Taking your example.

![Screenshot 2022-10-21 at 14 38 37](https://user-images.githubusercontent.com/505230/197120815-61a22340-085f-497b-bf61-0553d57374f3.png)

Clicking on [Aspect Ratio](https://wpt.fyi/results/?label=experimental&label=master&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2021-aspect-ratio).

![Screenshot 2022-10-21 at 14 39 18](https://user-images.githubusercontent.com/505230/197121065-9f897a9c-f90f-4410-a137-f564ecb4946a.png)

if I add to the [query `all(status:pass)`](https://wpt.fyi/results/?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2021-aspect-ratio%20all%28status%3Apass%29)

I get `155` on `158` hence 98.7%

![Screenshot 2022-10-21 at 14 48 28](https://user-images.githubusercontent.com/505230/197122622-6abcbe46-82d5-4a71-a2fc-e186b30bdd23.png)

Now let see with something more obvious/informative: Subgrid
I get `7` on `51` hence 13.7%

![Screenshot 2022-10-21 at 14 58 13](https://user-images.githubusercontent.com/505230/197123684-a1f1f3da-7ee9-4c3e-86b8-36384c59b0c1.png)

Aspect-ratio starts to be more usable and subgrid very hard to use in a reliable way.

**Comment by karlcow** [comment]
Basically, the score will be always lower than the smaller individual browser score.

**Comment by stof** [comment]
Should be closed as this is not implemented as the `Interop` score

**Comment by DanielRyanSmith** [comment]
Very right, this score is now available in production as of today 🙂
