### ISSUE TITLE
Strange error message when requesting diff view

### ISSUE THREAD

**Issue by kereliuk** [web-platform-tests/wpt.fyi#328]
**How to reproduce**
Visit [https://staging.wpt.fyi/results/?before=chrome@044cb1b9a7&after=edge](https://staging.wpt.fyi/results/?before=chrome@044cb1b9a7&after=edge).
I see `invalid character 'y' looking for beginning of value` with an HTTP status code of 400.

There probably isn't a full run for edge in this case (since there is for chrome I know), but we should handle the error more descriptively.

**Comment by Hexcles** [comment]
I'm not exactly sure why this is happening. The code is supposed to find the last run for the browser if no revision is specified, so it shouldn't matter if Edge doesn't have a run at 044cb1b9a7. The problem seems to only happen with Edge. I tried Safari and some other combinations of `before` & `after` and couldn't reproduce the issue.

**Comment by lukebjerring** [comment]
weirdly, it words fine with `edge@latest`:
https://staging.wpt.fyi/results/?before=edge@latest&after=chrome

Will dig into this (and at least verify that `edge` is a valid product spec...)

**Comment by lukebjerring** [comment]
lol. so... `edge` actually successfully decodes to `y�`

https://play.golang.org/p/tFZjxM7E8eS
