### ISSUE TITLE
Interop 2024: Edge Canary or separate Chrome and Edge

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#3580]
Switching to Chrome Canary as suggested in https://github.com/web-platform-tests/wpt.fyi/issues/3579 has some knock-on effects on the presentation here:

<img width="535" alt="image" src="https://github.com/web-platform-tests/wpt.fyi/assets/498917/c955b8e2-0273-4c30-90c4-1e47f1085b85">

Showing Chrome Canary + Edge Dev with a single score doesn't make sense as the score is often going to be different. In order to show "Edge Canary" we should actually have runs of Edge Canary.

Alternatively, we score Edge separately from Chrome. I think this has been suggested by @gsnedders but I can't find where now.

cc @dandclark

**Comment by dandclark** [comment]
My preference would be to move Edge to Canary as well.

**Comment by yisibl** [comment]
Will there be much difference in functionality between Chrome Canary and Edge?

**Comment by gsnedders** [comment]
> Alternatively, we score Edge separately from Chrome. I think this has been suggested by @gsnedders but I can't find where now.

https://github.com/web-platform-tests/interop/issues/96

> Will there be much difference in functionality between Chrome Canary and Edge Canary?

Using [yesterday's aligned run](https://wpt.fyi/results/?run_id=6209539419930624&run_id=5132998552322048&run_id=6327574541631488&run_id=5166121340108800), Chrome Dev has an overall interior score of 98.18%, whereas Edge Dev has an overall score of 95.62%.

I think [this](https://wpt.fyi/results/?q=%28label%3Ainterop-2021-position-sticky%20or%20label%3Ainterop-2021-transforms%20or%20label%3Ainterop-2022-dialog%20or%20label%3Ainterop-2022-scrolling%20or%20label%3Ainterop-2022-subgrid%20or%20label%3Ainterop-2022-webcompat%20or%20label%3Ainterop-2023-color%20or%20label%3Ainterop-2023-contain%20or%20label%3Ainterop-2023-cssmasking%20or%20label%3Ainterop-2023-events%20or%20label%3Ainterop-2023-flexbox%20or%20label%3Ainterop-2023-forms%20or%20label%3Ainterop-2023-grid%20or%20label%3Ainterop-2023-has%20or%20label%3Ainterop-2023-modules%20or%20label%3Ainterop-2023-offscreencanvas%20or%20label%3Ainterop-2023-property%20or%20label%3Ainterop-2023-pseudos%20or%20label%3Ainterop-2023-url%20or%20label%3Ainterop-2023-webcodecs%20or%20label%3Ainterop-2023-webcompat%29%20is%3Adifferent&run_id=6209539419930624&run_id=5132998552322048) shows the differences.

That said, it might be interesting to know how much of that difference is caused by platform (an Edge run on Linux or a Chrome run on Windows would presumably show that!).

**Comment by past** [comment]
> My preference would be to move Edge to Canary as well.

I support this as well, but I want to be clear that Chrome doesn't have the resources to work for this in 2023. We can only commit to getting results for Chrome Canary.

**Comment by foolip** [comment]
Here's a DevTools mockup of what this would look like if we switch to Chrome Canary and separate Chrome and Edge:

<img width="726" alt="image" src="https://github.com/web-platform-tests/wpt.fyi/assets/498917/780d65c0-8879-42d1-84ad-3f8ad3ab6edb">

----

If Edge also switches to Canary:

<img width="728" alt="image" src="https://github.com/web-platform-tests/wpt.fyi/assets/498917/154a053a-8f0f-4455-b121-b0b6cc248bc8">

**Comment by DanielRyanSmith** [comment]
This has been completed as of the Interop 2024 dashboard launch 🙂
