### ISSUE TITLE
Interop 2024: change the rounding behavior of the top-level scores

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#3640]
For the Interop 2024 dashboard, the Interop Team would like to change how the top-level scores are rounded. Rather than rounding down (`Math.floor()`) we'd like to use normal rounding (`Math.round()`) so that a score of 95.8% gets you 96 instead of 95.

The reason for the current rounding behavior goes back to Compat 2021 or Interop 2022, and IIUC it was motivated by not wanting to show 100 unless *all* tests are passing. Two possible options to avoid this:

- Special-case 100 only, and only give a score of 100 if *all* tests are passing (this has never happened)
- Switch from normal rounding to rounding down at a breakpoint like 97.5%, so that the final percentage points are "harder"

cc @jensimmons

**Comment by DanielRyanSmith** [comment]
I can take care of this, but I have some clarifying questions. 🙂

For reference, each raw Interop score is being represented as number between 0 and 1000 ([you can see this in the frozen 2022 scores](https://github.com/web-platform-tests/wpt.fyi/blob/main/webapp/static/interop-2022-stable.csv)). When we display these numbers on the Interop dashboard, we divide by 10 and display that number as the percentage (e.g. 886 -> 88.6%).

In this regard, rounding down using `Math.floor()` only occurs when calculating the total% of a browser's score (e.g. A browser's average across all focus areas equals 706.723, decimals are dropped, average score = 70.6%).

> we'd like to use normal rounding (Math.round()) so that a score of 95.8% gets you 96 instead of 95.

Does this mean we want to round to the nearest whole number for each percentage and no longer use decimals?

In the case of avoiding rounding up to 100% - would we like to keep the single decimal place for instances of >99% that aren't actually 100%? (e.g. displaying 99.7% rather than rounding to either 99% or 100%)

**Comment by DanielRyanSmith** [comment]
Completed with the launch of the Interop 2024 dashboard
