### ISSUE TITLE
Stable channels are outdated

### ISSUE THREAD

**Issue by SebastianZ** [web-platform-tests/wpt.fyi#3735]
E.g. https://wpt.fyi/results/shadow-dom?label=master&label=stable&aligned&view=interop&q=label%3Ainterop-2024-dsd shows

![Results for Declarative Shadow DOM tests on outdated stable versions of browsers](https://github.com/web-platform-tests/wpt.fyi/assets/958943/ac497d72-6a2b-488d-a748-1f91c4d289e7)

I.e. the test results are from January 22, and the browser versions marked as "Stable" are actually one version behind for Safari (which is now at 17.3) and two versions behind for the other browsers (Chrome is at 122, Edge 122, and Firefox 123).

This also results in https://wpt.fyi/interop-2024?stable showing wrong numbers.

Interestingly, if I change the channel of Firefox to "Experimental", [all versions are correct](https://wpt.fyi/results/shadow-dom?label=master&product=chrome[stable]&product=edge[stable]&product=firefox[experimental]&product=safari[stable]&aligned&view=interop&q=label%3Ainterop-2024-dsd). Though that works only when Firefox's channel is changed, not on the others.

Sebastian

**Comment by KyleJu** [comment]
@SebastianZ it is due to missing [Firefox stable runs](https://github.com/web-platform-tests/wpt/issues/44366), our aligned  stable runs are behind on the homepage. The last available Firefox run was at [Feb 22](https://wpt.fyi/runs?label=master&label=stable&max-count=100&product=chrome&product=firefox&product=safari).

**Comment by SebastianZ** [comment]
Oh, I see, thank you for the hint!

Sebastian
