### ISSUE TITLE
Drilling into file results in diff view doesn't work

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#410]
Start at https://staging.wpt.fyi/results/resource-timing?product=chrome[experimental]&product=chrome[stable]&diff=true

Try to click "resource_initiator_types.html". That leads to a page that looks like this:
![image](https://user-images.githubusercontent.com/498917/43826336-606ac96c-9af7-11e8-8a0c-b3f5bd79397c.png)

No results. In this I'd like to see highlighted the reason for the diff numbers not adding up, i.e. which test results aren't the same.

**Comment by Hexcles** [comment]
The empty view is because of an uncaught exception, which itself can be easily fixed.

However, I don't think we ever support any meaningful diffing of an individual test result. The prod wpt.fyi actually shows an empty diff column, but I'm not sure if we accidentally broke something even before the current prod version. I'd need the original author of the diffing feature to confirm @lukebjerring  :)

If that's the case, then the more proper fix would be to hide the diff column completely when drilling down to individual tests (but we still want to keep the diff parameter in URL so that when users go back up diff will reappear).

**Comment by lukebjerring** [comment]
You're right, the single file view still needs addressing. Feel free to make the calls on the updated behavior :)
