### ISSUE TITLE
No new runs since Aug 8

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#432]
https://wpt.fyi/results/?label=stable
https://wpt.fyi/results/?label=experimental
https://wpt.fyi/test-runs

All of these suggest that eea0b54014 is the latest commit for which we have results, which landed at 2018-08-07T11:50:18Z, although the runs finished on Aug 8.

Since then, no new runs.

@Hexcles, can you first check if the results receiver has been getting any results posted to it since then? If not, please file an issue at https://github.com/web-platform-tests/results-collection for @jugglinmike to investigate.

**Comment by foolip** [comment]
See also https://github.com/web-platform-tests/wpt.fyi/issues/63.

**Comment by foolip** [comment]
@jugglinmike might this still be the `global=jsshell` problem blocking results collection? If so, can we put in a workaround ASAP to get new results uploaded?

**Comment by jugglinmike** [comment]
Here's a breakdown of where we're at:

- 2018-08-07 - [the regression landed upstream (in WPT)](https://github.com/web-platform-tests/wpt/pull/12334)
- 2018-08-06
  - [filed an incident report in the results-collector](https://github.com/web-platform-tests/results-collection/issues/590)
  - [reported the regression in WPT](https://github.com/web-platform-tests/wpt/issues/12366)
  - implemented two alternatives to fix the regression: https://github.com/web-platform-tests/wpt/pull/12360 & https://github.com/web-platform-tests/wpt/pull/12368
- 2018-08-13 - [reported the problem in ecosys-infra "snippets" e-mail](https://groups.google.com/a/chromium.org/forum/#!msg/ecosystem-infra/Hq0k6m7Brao/pebOmJmKDQAJ)
- 2018-08-14 - [recommended reverting the regression](https://github.com/web-platform-tests/wpt/pull/12482)

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/pull/12360 was merged an hour ago.

https://wpt.fyi/results/?label=stable and https://wpt.fyi/results/?label=experimental now have Chrome runs for 86e157b387, but 86e157b387 is an earlier commit than the merge_pr_12360 tag, so it can't be because of that. (Filed https://github.com/web-platform-tests/wpt.fyi/issues/441 about the mixed runs in the UI.)

**Comment by foolip** [comment]
@jugglinmike, https://github.com/web-platform-tests/wpt/pull/12368 is still open, but should https://github.com/web-platform-tests/wpt/pull/12360 alone be enough to resolve the issue?

**Comment by jugglinmike** [comment]
Yup, for our purposes, we can consider the issue resolved.

We were able to collect results before my fix was accepted because [I implemented a crude workaround in results-collection](https://github.com/web-platform-tests/results-collection/commit/f52dd86c6e445701c5646bf5954758d00c11f418). With the fix in place, the workaround is no longer necessary, so [I removed it just now](https://github.com/web-platform-tests/results-collection/commit/6479d2aca47b9cb6e03992428ea52b1d9210932e).

**Comment by foolip** [comment]
Thank you @jugglinmike, too bad about the timing of the workaround. Alright, let's leave this open for another 24 hours until we see "stable runs" in https://foolip.github.io/ecosystem-infra-rotation/ go green. We expect experimental runs to occasionally get old as neither Edge or Safari are running reliably.

For everyone following along, https://github.com/web-platform-tests/wpt/pull/12493 is how I think we should avoid a similar situation going forward. Reverting is a frequent and non-confrontational event in Chromium, and I hope the same model will work in WPT.

**Comment by foolip** [comment]
There are still no new runs for Edge or Safari. @jugglinmike, do you know why?

**Comment by jugglinmike** [comment]
Yesterday's collection failed due to disk space utilization (when it rains, it pours). This time, it was Sauce Connect logs. I wasn't aware that Sauce Connect appends to the file instead of truncating it, so they've steadily been growing in size since April.

As a stop-gap, I manually deleted those giant log files. That's why today's collection is advancing is expected. As a longer-term solution, [I implemented log rotation](https://github.com/web-platform-tests/results-collection/commit/b3ba7f595d4275bdae012ea817477b8b268d77d6).

I'm sorry for not reporting this sooner!

**Comment by foolip** [comment]
Thanks @jugglinmike, I'll check back again tomorrow and see if the rain has let up a bit and a shiny new run comes out from behind the clouds :)

**Comment by foolip** [comment]
The clouds have cleared:
https://wpt.fyi/results/?label=stable

https://github.com/web-platform-tests/wpt.fyi/issues/441 is still a problem, but closing this issue. Thanks @jugglinmike for getting us back on track!

**Comment by jugglinmike** [comment]
Sure thing. I'll keep an eye out for further storms, as usual
