### ISSUE TITLE
Clean up web component tests

### ISSUE THREAD

**Issue by mdittmer** [web-platform-tests/wpt.fyi#470]
Our web component tests currently contain a lot of silly things (like checking the existence/type of every property), and not enough testing of correct behaviour.

If we can get a few good examples checked in, then getting coverage over all web components can be a team effort (by having non-WCT-experts follow conventions established by a few good examples).

**Comment by Hexcles** [comment]
Besides, because of #435 , many tests have been broken/out-of-date for an extended period of time and are non-trivial to fix, so I disabled a bunch of tests in 34bb95b0db4a0161ba670e17bf3f7a779903b042. They need to fixed/removed.

I'd hope someone with more experience in web component tests can spend some time to write a few good tests (perhaps from scratch) so that we can use as examples. I don't know the norm or convention of web component tests, e.g. whether we should even check all the properties.

An unrelated note: when I was playing with the tests, I noticed that the versions of `mocha` and `sinon` that shipped with `web-component-tester` of Polymer 2 were pretty old. There have been some breaking API changes, so watch out when you look for documentation.

**Comment by lukebjerring** [comment]
Been working on this with
- https://github.com/web-platform-tests/wpt.fyi/pull/565
- https://github.com/web-platform-tests/wpt.fyi/pull/552
- https://github.com/web-platform-tests/wpt.fyi/pull/545
- https://github.com/web-platform-tests/wpt.fyi/pull/546

**Comment by lukebjerring** [comment]
`suite.skip` is no longer present, so I'm closing this since we have a few good example suites.
