### ISSUE TITLE
Expose full datastore contents publicly (via API or static dump)

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#636]
In addition to the data in our GCS buckets, entries in datastore are needed by the wpt.fyi frontend.

In order to facilitate offline data analysis, this data should be made readily available, perhaps via https://wpt.fyi/api/runs, or perhaps in some other form. As a secondary motivation, it's also important that it's possible to fork wpt.fyi with the full historical data.

Context: @s3ththompson will be doing some data analysis for Bocoup, generating cool graphs and inspiration for us all.

**Comment by Hexcles** [comment]
Whenever a "run" is returned by any of our APIs, it should already contain all the information (all the fields) in Datastore.

@s3ththompson what information are you looking for?

**Comment by foolip** [comment]
> Does /api/runs not provide the necessary information already?

Possibly, if it can be paginated without missing anything due to changes in the interim. Is that possible?

**Comment by lukebjerring** [comment]
Hmmmm - yes, "paginate" with the `to` param being set to the timestamp of the last item in the previously returned result.

**Comment by foolip** [comment]
OK, that sort of pagination sounds like it should work. Can we document how to do it in this repo for forkability?

**Comment by s3ththompson** [comment]
@foolip @lukebjerring that should be enough for me.

So to clarify, all wpt.fyi data for runs is accessible through https://wpt.fyi/api/runs & https://wpt.fyi/api/interop and consists of 4 separate "sources":
1. Datastore metadata that includes test run time information, labels, and a unique run ID (am I missing any other metadata?)
2. The full report for the run, including test and subtest results (>100mb), stored at `gs://wptd-results`
3. An offline-generated summary for the run including just pass/fail numbers for subtests (~2mb), stored at `gs://wptd`
4. An offline-generated summary of interop rates among browsers (~4mb), stored at `gs://wptd-metrics`

It looks like paging through the runs & interop api is the easiest way to download the data for offline analysis (rather than rsyncing the `gs://` buckets)...

One more question: I see that summaries are generated here: https://github.com/web-platform-tests/wpt.fyi/blob/master/results-processor/wptreport.py#L243 are interop rates still computed from https://github.com/web-platform-tests/results-analysis? Is there a benefit to re-computing historical interop rates based on the latest results-analysis image?

**Comment by s3ththompson** [comment]
Also, I'm planning to contribute some documentation once I successfully scrape the right data.

**Comment by foolip** [comment]
@lukebjerring, is it possible to get all runs if one doesn't know what the products are? I guess a script for this would just hardcore the four?

**Comment by Hexcles** [comment]
> So to clarify, all wpt.fyi data for runs is accessible through https://wpt.fyi/api/runs & https://wpt.fyi/api/interop and consists of 4 separate "sources":

Yes, although only the first two are really "sources" while the latter two are derivatives.

> Datastore metadata that includes test run time information, labels, and a unique run ID (am I missing any other metadata?)

We have two "tables", returned by /api/runs and /api/interop respectively. You will see all the metadata in the two tables in example responses from these two APIs: https://github.com/web-platform-tests/wpt.fyi/blob/master/api/README.md

> It looks like paging through the runs & interop api is the easiest way to download the data for offline analysis (rather than rsyncing the gs:// buckets)...

That's correct. We tried to impose [a well-defined schema for storage paths](https://github.com/web-platform-tests/wpt.fyi/blob/master/docs/gcs.md), but the fact is the schema has been changed a few times and we haven't bothered migrating all the previous runs.

**Comment by foolip** [comment]
A documented way to get all runs would be great for https://github.com/foolip/ecosystem-infra-stats/issues/17.

**Comment by foolip** [comment]
I ran into trouble: https://github.com/web-platform-tests/wpt.fyi/issues/733

**Comment by foolip** [comment]
More trouble: https://github.com/web-platform-tests/wpt.fyi/issues/734

**Comment by foolip** [comment]
With the use of datastore renaming as in https://github.com/web-platform-tests/wpt.fyi/issues/743, the importance of having a reliable way to get all runs increases. Otherwise when people revert to scanning the GCS bucket as I did they'll still get those bad runs.

**Comment by lukebjerring** [comment]
FYI #772 added the ability to paginite __IFF__ you use a max-count parameter.
So https://staging.wpt.fyi/api/runs?max-count=500 will return a `wpt-next-page` HTTP header.
Then you can call https://staging.wpt.fyi/api/runs?page=[token]
