### ISSUE TITLE
Navigation is broken

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt.fyi#653]
Start at https://staging.wpt.fyi/results/?sha=d647a1bc74&product=safari%5Bstable%5D&product=safari%5Bexperimental%5D&diff with no flags enabled (discovered with query builder and diff filter enabled, but repros without)

Then, click 2dcontext. The URL changes to https://staging.wpt.fyi/results/2dcontext?sha=d647a1bc74&product=safari%5Bstable%5D&product=safari%5Bexperimental%5D&diff but the view does not, the top-level view is still shown!

Now, click 2dcontext again. Now you will end at the right view. From here, click the "wpt" above the table to navigate back to the top level. Here something very bizarre happens. The URL is https://staging.wpt.fyi/results/?sha=d647a1bc74&product=safari%5Bstable%5D&product=safari%5Bexperimental%5D&diff but the view is the contents of 2dcontext with "2dcontext/" pretended to each path.

Overall, it seems like the navigation is delayed by one step, plus some confusion of state.

**Comment by foolip** [comment]
Screenshot of the final bizarre state here. I discovered this in Chrome for Android, not verified in a desktop browser.

![screenshot_20181013-124018](https://user-images.githubusercontent.com/498917/46904528-8a6c8300-cee5-11e8-8cdc-1326798a2524.png)

**Comment by CYBAI** [comment]
I can reproduce this issue on Firefox Nightly 64.0a1.

**Comment by CYBAI** [comment]
After doing more investigation, I found we'll trigger `click` event and do `submit` so the correct `this.path` is overridden when doing the `submit` (the `window.location` is still `https://staging.wpt.fyi/results/?sha=` instead of `https://staging.wpt.fyi/results/2dcontext?sha=`)

1. Update `path` correctly from `click` event via the `event.target`

https://github.com/web-platform-tests/wpt.fyi/blob/3dea9f3be299f2461151a6b60ab03a398bf5f659/webapp/components/self-navigator.html#L96-L103

2. The observer will trigger `onLocationUpdated` so it will trigger the `submit`

https://github.com/web-platform-tests/wpt.fyi/blob/3dea9f3be299f2461151a6b60ab03a398bf5f659/webapp/components/self-navigator.html#L67-L72

3. the `submit` is triggered 3 times and `path` is `/` in last 2 times

https://github.com/web-platform-tests/wpt.fyi/blob/3dea9f3be299f2461151a6b60ab03a398bf5f659/webapp/components/wpt-results.html#L490-L500

I'm wondering if the correct patch for this issue is to avoid the last 2 times `submit`; I think it should be fine to only execute the `click` event when we click on the test name (ex. `/2dcontext`)?

**Comment by lukebjerring** [comment]
Thanks for digging into the cause; I'll play around and have a patch later today.
