### ISSUE TITLE
/api/search is returning an empty result set

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt.fyi#759]
URL:
https://wpt.fyi/results/?sha=89188af975&label=stable&products=chrome,edge,firefox,safari

If you change the product set to not include any of the browsers, results are returned just fine - seems like a case of poisoned cache?

**Comment by Hexcles** [comment]
The default homepage is now broken. This is bad(TM).

Do we know why it happens? Luke suggested it was cache and I'm looking into how to purge the cache (unfortunately it's not easy because we only have access to memcache on AppEngine standard so I'd need to upload an ad-hoc version to prod with a special endpoint to purge the cache which is risky on its own).

I'm more concerned that even if I did this, the cache would be corrupted again if we don't understand the root cause.

**Comment by Hexcles** [comment]
#762 implemented an endpoint to purge memcache which temporarily solved the issue for now. We still don't fully understand the root cause of this issue.

**Comment by mdittmer** [comment]
#768 guards us against cache poisoning with empty result sets. It does not, however, save us from inaccurate non-empty results. @lukebjerring should we close this and open a new issue if bad non-empty sets start cropping up?

**Comment by lukebjerring** [comment]
Yep.
