### ISSUE TITLE
Error from revision announcer

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/wpt.fyi#802]
At approximate 12:08 UTC on 2018-11-23, the results-collection system queried the revision announcer for the current "daily" revision. The response body was not JSON formatted, so results collection did not occur.

Unfortunately, the logs describing the failure are very vague, so I cannot report the HTTP status code of the response nor the contents of the body. [I have updated the relevant script to output that information in the case of failure](https://github.com/web-platform-tests/results-collection/commit/5806e0ccd44b76eb7a1ff91bd5e13856f63e4d9f), but it may be possible to diagnose the issue from wpt.fyi's logs alone. A few details that may be relevant:

- The system successfully responded to an identical request which was issued one minute prior to the failed request
- The failed response arrived only after a delay of 150 seconds

The good news is that this is the first time we've experienced a problem with this request since [we introduced it a couple months ago](https://github.com/web-platform-tests/results-collection/pull/596).

**Comment by mdittmer** [comment]
It appears that the revision announcer was restarted "by not fault of our own". Perhaps a security update for the underlying AppEngine instance.

AFAICT, there are two ways to respond to the situation:

1. **Replicate the announcer.** This will drastically reduce the probability that collectors fail to hear back from the announcer. This has a potentially serious down side though: It would be possible, in principle, for two requests, A and B, issued in that order, to see out-of-order results with respect to each other because they got routed to different announcer instances (e.g., A sees today's new daily and B sees yesterday's old daily).
1. **Make clients resilient to temporary announcer outages.** IIUC `wpt-pr-bot` behaves this way by construction because it polls every two minutes, and if a request fails, it just tries again two minutes later. What I don't know is how much work it is to implement retries in other revision announcer clients.

I prefer the latter solution because it does not expose us to race conditions, even if results collection gets delayed by `[announcer outage time]` (this was <8 minutes after last restart). That said, I don't own the client code in question.

@jugglinmike what are your thoughts on the trade-offs here?

**Comment by jugglinmike** [comment]
The second solution sounds good to me, too. Could you recommend an appropriate polling frequency and timeout duration based on your understanding of the expected downtime? This would allow collectors to detect more serious kinds of service outage, report the problem, and avoid unnecessary work. To that end, it may even be appropriate to include that information as a caveat in the API documentation.

**Comment by mdittmer** [comment]
Based on the logs I would recommend polling every 1-2 minutes. A downtime of 10 minutes would constitute a non-transient failure. (I would suspect much less than 10 minutes to restart the announcer, but these conservative numbers should avoid false positives.)

**Comment by mdittmer** [comment]
@jugglinmike feel free to use and/or link back to this bug regarding any work on the collectors that needs to be updated to retry. I'll leave it up to you when to close this bug since the work resides in a different repo.

**Comment by jugglinmike** [comment]
> @jugglinmike feel free to use and/or link back to this bug regarding any work on the collectors that needs to be updated to retry

Thanks! Mind taking a look? https://github.com/web-platform-tests/results-collection/pull/633

> I'll leave it up to you when to close this bug since the work resides in a different repo.

It still seems like future results collection projects ought to be informed of this recommendation. As long as we're going with the second solution, we should document it so other folks contributing results will know what to expect: https://github.com/web-platform-tests/wpt.fyi/pull/811

**Comment by mdittmer** [comment]
Looks like this is both implemented and documented. @jugglinmike are we ready to close this issue?

**Comment by jugglinmike** [comment]
We are!
